<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_Sign in_fi-simple-main fi-width-lg</name>
   <tag></tag>
   <elementGuidId>127f804f-a317-4694-a85b-f1641194178b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.fi-simple-main.fi-width-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>7a5df491-505c-4c29-a5ad-ec535ab9cdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-simple-main fi-width-lg</value>
      <webElementGuid>844f316b-6fa5-4545-9807-576e6ce01855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                
    

    
        
                    
    

            


    

            
            Sign in
        
    

    


        
                                                                                                                
        
                            
                    
    

    
        
                                                
        
                            
                    
        
                                                
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Email address*
                                
                            
                        

                        
                    
                

                
            

            
        
    

            
            

                            
    

    
        
    

    


    
            

            

            
        
    

                
                    

                                                                        
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Password*
                                
                            
                        

                        
                    
                

                
            

            
        
    

            
            

                            
    

    
        
    

            
            

            

                            
                                            
        
        
            
  
  
            
                    

        
        
                                            
        
        
            
  
  
            
                    

        
        
                    
                
            
        
    


    
            

            

            
        
    

                
                    

                                                                        
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Remember me
                            
                        

                        
                    
                

                
            

            
        
    

    

                
                    

                                            

                        
                    

                                            

        

    
        
                                                
        
                            
                    
    

    

        
                                    
        
        
        
                                            
    
    
                
    
    
            
                                                
                        Sign in                    
                            
                            
            
            
                    

        
        
            
        
    


    

                
                    

                                            

        

                
                    

                                                                        
        
                    

                                                                                                            
    

                
        
    

    
    

    

            </value>
      <webElementGuid>e7728801-33df-41de-bf0e-eef47bfe3653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fi dark&quot;]/body[@class=&quot;fi-body fi-panel-admin&quot;]/div[@class=&quot;fi-simple-layout&quot;]/div[@class=&quot;fi-simple-main-ctn&quot;]/main[@class=&quot;fi-simple-main fi-width-lg&quot;]</value>
      <webElementGuid>1d9d6323-5947-4ea3-b371-2fd25762cd80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main</value>
      <webElementGuid>46bfba0c-bbb5-4570-913c-cced6fa111e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//main[(text() = '
                
    

    
        
                    
    

            


    

            
            Sign in
        
    

    


        
                                                                                                                
        
                            
                    
    

    
        
                                                
        
                            
                    
        
                                                
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Email address*
                                
                            
                        

                        
                    
                

                
            

            
        
    

            
            

                            
    

    
        
    

    


    
            

            

            
        
    

                
                    

                                                                        
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Password*
                                
                            
                        

                        
                    
                

                
            

            
        
    

            
            

                            
    

    
        
    

            
            

            

                            
                                            
        
        
            
  
  
            
                    

        
        
                                            
        
        
            
  
  
            
                    

        
        
                    
                
            
        
    


    
            

            

            
        
    

                
                    

                                                                        
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Remember me
                            
                        

                        
                    
                

                
            

            
        
    

    

                
                    

                                            

                        
                    

                                            

        

    
        
                                                
        
                            
                    
    

    

        
                                    
        
        
        
                                            
    
    
                
    
    
            
                                                
                        Sign in                    
                            
                            
            
            
                    

        
        
            
        
    


    

                
                    

                                            

        

                
                    

                                                                        
        
                    

                                                                                                            
    

                
        
    

    
    

    

            ' or . = '
                
    

    
        
                    
    

            


    

            
            Sign in
        
    

    


        
                                                                                                                
        
                            
                    
    

    
        
                                                
        
                            
                    
        
                                                
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Email address*
                                
                            
                        

                        
                    
                

                
            

            
        
    

            
            

                            
    

    
        
    

    


    
            

            

            
        
    

                
                    

                                                                        
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Password*
                                
                            
                        

                        
                    
                

                
            

            
        
    

            
            

                            
    

    
        
    

            
            

            

                            
                                            
        
        
            
  
  
            
                    

        
        
                                            
        
        
            
  
  
            
                    

        
        
                    
                
            
        
    


    
            

            

            
        
    

                
                    

                                                                        
        
                            
                    
    

            
            

            
                

                                    
                        

                                                    
                                Remember me
                            
                        

                        
                    
                

                
            

            
        
    

    

                
                    

                                            

                        
                    

                                            

        

    
        
                                                
        
                            
                    
    

    

        
                                    
        
        
        
                                            
    
    
                
    
    
            
                                                
                        Sign in                    
                            
                            
            
            
                    

        
        
            
        
    


    

                
                    

                                            

        

                
                    

                                                                        
        
                    

                                                                                                            
    

                
        
    

    
    

    

            ')]</value>
      <webElementGuid>2978672e-46cf-426e-bfa4-d1634ae339e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
