<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Photo path_filepond--drop-label-eiqgi6wca</name>
   <tag></tag>
   <elementGuidId>a60354b5-9554-483a-bda8-0c8a2d6f8da7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='filepond--drop-label-eiqgi6wca']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filepond--drop-label-eiqgi6wca</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Drag &amp; Drop your files or Browse&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>21709ef0-d1bb-4507-af38-7e43cc3d3080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>filepond--browser-eiqgi6wca</value>
      <webElementGuid>946f81ec-abad-4b2e-b8f4-fd347748ec12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filepond--drop-label-eiqgi6wca</value>
      <webElementGuid>38861d5a-7661-480c-a907-a41363bd29ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; Drop your files or  Browse </value>
      <webElementGuid>7a1327a8-4c27-44ca-b74c-485d0eb94f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filepond--drop-label-eiqgi6wca&quot;)</value>
      <webElementGuid>35e53542-2ac7-481c-9b91-454bd8e38ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='filepond--drop-label-eiqgi6wca']</value>
      <webElementGuid>371dd40b-d1a4-4bb3-a83e-e70cdee18a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form.photo_path']/div/div/div/label</value>
      <webElementGuid>175596eb-75d7-46e5-80cc-15039a3b933d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo path'])[1]/following::label[1]</value>
      <webElementGuid>4ee9813c-624e-443b-82ae-155f30b2175c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::label[1]</value>
      <webElementGuid>3133f4ac-992b-4048-9c8c-34b4c4593400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/preceding::label[1]</value>
      <webElementGuid>0802d12b-9b3e-4dae-a954-c43835d3d17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drag &amp; Drop your files or']/parent::*</value>
      <webElementGuid>ea44b6d1-a385-49dd-a378-14ab50708bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/div/label</value>
      <webElementGuid>17249b90-45f2-4bb6-9e31-ba26623ec8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'filepond--drop-label-eiqgi6wca' and (text() = 'Drag &amp; Drop your files or  Browse ' or . = 'Drag &amp; Drop your files or  Browse ')]</value>
      <webElementGuid>33f1ec79-384b-4911-80c8-3ed2f8cc8e76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
