<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_active_fi-icon fi-size-md</name>
   <tag></tag>
   <elementGuidId>850bbb69-4260-4c36-95de-9f51947a6c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='active'])[3]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Actions View Edit Delete&quot;i] >> internal:label=&quot;Actions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>7934b655-1e4a-4fd4-8ee3-e15caac99638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-icon fi-size-md</value>
      <webElementGuid>0739a737-e374-490d-9a45-0c50d7d7616c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>3d62f644-b81f-4bd7-aa0e-de2631212e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>de8f1637-3862-419e-be85-ee31ed9869e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>9bbc5215-436a-4cd1-bfeb-fcae30344e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ab81ac6f-6c41-410e-be94-7cd0f11418c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>f6395722-018c-4bf8-be90-0899ee80503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fi dark&quot;]/body[@class=&quot;fi-body fi-panel-admin fi-body-has-navigation fi-body-has-topbar&quot;]/div[@class=&quot;fi-layout&quot;]/div[@class=&quot;fi-main-ctn&quot;]/main[@class=&quot;fi-main fi-width-7xl&quot;]/div[@class=&quot;fi-page fi-resource-list-records-page fi-resource-employees&quot;]/div[@class=&quot;fi-page-header-main-ctn&quot;]/div[@class=&quot;fi-page-main&quot;]/div[@class=&quot;fi-page-content&quot;]/div[@class=&quot;fi-sc  fi-sc-has-gap fi-grid&quot;]/div[@class=&quot;fi-grid-col&quot;]/div[@class=&quot;fi-sc-component&quot;]/div[@class=&quot;fi-ta&quot;]/div[@class=&quot;fi-ta-ctn fi-ta-ctn-with-header&quot;]/div[@class=&quot;fi-ta-content-ctn&quot;]/table[@class=&quot;fi-ta-table&quot;]/tbody[1]/tr[@class=&quot;fi-ta-row fi-clickable&quot;]/td[@class=&quot;fi-ta-cell&quot;]/div[@class=&quot;fi-ta-actions&quot;]/div[@class=&quot;fi-dropdown&quot;]/div[@class=&quot;fi-dropdown-trigger&quot;]/button[@class=&quot;fi-color fi-color-primary fi-text-color-600 hover:fi-text-color-500 dark:fi-text-color-400 dark:hover:fi-text-color-300 fi-icon-btn fi-size-md fi-ac-icon-btn-group&quot;]/svg[@class=&quot;fi-icon fi-size-md&quot;]</value>
      <webElementGuid>6adfa599-693f-4aaa-8a3d-d38965fe427e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='active'])[3]/following::*[name()='svg'][1]</value>
      <webElementGuid>c33ebd32-e562-4419-9793-54167db13ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bambang'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>9faa5cc7-0106-465e-90df-db375cd360bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[3]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>f451c547-0189-4ca9-a2e1-b01e33f2f5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[3]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>8bb28017-b106-4d92-bdbd-a635dbae11cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
